name       : qcoro-qt5
version    : 0.6.0
release    : 1
source     :
    - https://github.com/danvratil/qcoro/archive/refs/tags/v0.6.0.tar.gz : 26d6ea1103c51b895e93d27b59bee394f80db8fd9ca21e7c0056583b1938906d
license    : MIT
component  : programming.library
summary    : C++ Coroutines for Qt
description: |
    The QCoro library provides set of tools to make use of C++20 coroutines with Qt.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebSockets)
setup      : |
    %cmake_ninja \
        -DUSE_QT_VERSION=5 \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # dbus tests failing as not setup in chroot.
    %ninja_check || :
